name: customized_streams
description: >
  CustomizedStreams is an implementation of the rxdart 
  programming, leveraging the native Dart Streams api for stream transformation.
version: 1.0.16

homepage: https://github.com/vo9312/customized_streams

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  analyzer: ">=0.34.0 <=0.40.0"
  rxdart: ^0.24.1

dev_dependencies:
  test: ^1.15.3
